[package]
name = "runlike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.4", features = ["derive"] }
nix = "0.26.2"
privdrop = "0.5.3"
snafu = "0.7.4"
sysinfo = "0.29.2"
