[package]
name = "runlike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.146"
nix = "0.26.2"
snafu = "0.7.4"
